# Generated by Django 4.2.30 on 2026-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0003_requestlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlogs",
            name="ip_address",
            field=models.CharField(default=100, max_length=100),
        ),
        migrations.AddField(
            model_name="requestlogs",
            name="method",
            field=models.CharField(default="postget", max_length=50),
        ),
    ]
