# Generated by Django 4.2.30 on 2026-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0004_requestlogs_ip_address_requestlogs_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
