# Generated by Django 4.2.30 on 2026-06-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0005_signup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="signup",
            old_name="name",
            new_name="username",
        ),
    ]
